CapaPresentacion/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaPresentacion.Models;
using Model.Entity;

namespace CapaPresentacion.Controllers
{
    public class ClienteController : Controller
    {
        // GET: Cliente
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult listar()
        {
            var data = new Model.Neg.ClienteNeg().ReadC();
            var json = new { data };
            return Json(json, JsonRequestBehavior.AllowGet);
        }
        
        [HttpGet]
        public JsonResult listarD()
        {
            var data = new Model.Neg.ClienteNeg().Read();
            var json = new { data };
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult listarC()
        {
            var data = new Model.Neg.ClienteNeg().ReadC();
            var json = new { data };
            return Json(json, JsonRequestBehavior.AllowGet);
        }



        [HttpPost]
        public JsonResult InsertC(Cliente_Venta OCliente)
        {
            bool respuesta = true;
            Model.Neg.ClienteNeg.Agregar(OCliente);          

            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult InsertR(Cliente_Venta OCliente)
        {
            
            int ID = Model.Neg.ClienteNeg.AgregarR(OCliente);

            return Json(ID);
        }

        [HttpPost]
        public JsonResult Buscar(Cliente_Venta OCliente)
        {
            Cliente_Venta Cliente = new Model.Neg.ClienteNeg().Buscar(OCliente);

            return Json(Cliente);
        }

        [HttpPost]        
        public JsonResult Guardar(Cliente_Venta OCliente)
        {
            bool respuesta = true;
            try
            {
                if (OCliente.ID_Cliente == 0)
                {
                    Model.Neg.ClienteNeg.Agregar(OCliente);
                }
                else
                {
                    Model.Neg.ClienteNeg.Actualizar(OCliente);
                }
            }
            catch
            {
                respuesta = false;
            }

            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }

       
        public JsonResult Elimina(int IdCliente)
        {
            bool respuesta = true;
            try
            {
                Model.Neg.ClienteNeg.Eliminar(IdCliente);
            }
            catch
            {
                respuesta = false;
            }
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }
    }
}

CapaPresentacion/Controllers/ServicioController.cs
 using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.Entity;
using Model.Neg;

namespace CapaPresentacion.Controllers
{
    public class ServicioController : Controller
    {
        // GET: Servicio

        private FacturaNeg objFacturaNeg;
        private ProductoNeg objProductoNeg;
        private DetalleFacturaNeg objDetalleFacturaNeg;
        public ServicioController()
        {           
            objFacturaNeg = new FacturaNeg();
            objProductoNeg = new ProductoNeg();
            objDetalleFacturaNeg = new DetalleFacturaNeg();
        }

        public ActionResult Factura(int ID)
        {
            Factura Cabeza = new FacturaNeg().VistaF(ID);
            int ID_Contrato = objFacturaNeg.BuscarC(ID);
            List<Servicios> ListadoDetalle = new FacturaNeg().VistaDF(ID);
            ViewData["Fecha"] = Cabeza.Fecha;
            ViewData["Nombre"] = Cabeza.Nombre;
            ViewData["Cel"] = Cabeza.Telefono;
            ViewData["ID"] = Cabeza.ID_Factura;
            ViewData["Suma"] = Cabeza.Subtotal;
            ViewData["Descuento"] = Cabeza.Descuento;
            ViewData["Subtotal"] = Cabeza.Total - Cabeza.Impuesto;
            ViewData["Iva"] = Cabeza.Impuesto;
            ViewData["Total"] = Cabeza.Total;
            ViewData["ID_C"] = ID_Contrato;
            ViewData["Direccion"] = Cabeza.Direccion;
            return View(ListadoDetalle);
        }

        public ActionResult Recibo(int ID)
        {
            Recibo Cabeza = new FacturaNeg().VistaR(ID);
            ViewData["ID"] = ID;
            ViewData["Fecha"] = Cabeza.Fecha;
            ViewData["Nombre"] = Cabeza.Nombre;
            ViewData["Metodo"] = Cabeza.Forma;
            ViewData["Monto"] = Cabeza.Monto;
            ViewData["Efectivo"] = Cabeza.Efectivo;
            ViewData["Cheque"] = Cabeza.Cheque;
            ViewData["Concepto"] = Cabeza.Concepto;
            ViewData["Banco"] = Cabeza.Banco;
            return View();
        }

        public ActionResult Almacen()
        {
            return View();
        }

        public ActionResult Proforma()
        {
            return View();
        }

        [HttpPost]
        public JsonResult InsertS(Servicios OServicio)
        {
            bool respuesta = true;
            try
            {
                if (OServicio.ID_Servicio == 0)
                {
                    ProductoNeg.Agregar(OServicio);
                }
                else
                {
                    ProductoNeg.Actualizar(OServicio);
                }
            }
            catch
            {
                respuesta = false;
            }
            
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public int GuardarRecibo(Recibo ORecibo)
        {            
            Recibo objRecibo = new Recibo(ORecibo.Fecha, ORecibo.ID_Evento, 
            ORecibo.Monto, ORecibo.Forma , ORecibo.Efectivo, ORecibo.Cheque, ORecibo.Banco, ORecibo.Concepto);
            int ID = objProductoNeg.AgregarR(objRecibo);
            return ID;
        }

        public JsonResult Elimina(int IdAlmacen)
        {
            bool respuesta = true;
            try
            {
                Model.Neg.ProductoNeg.Eliminar(IdAlmacen);
            }
            catch
            {
                respuesta = false;
            }
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Transporte()
        {
            return View();
        }
        public ActionResult Historial()
        {
            return View();
        }
        public JsonResult Obtener(int IdAlmacen)
        {
            Servicios ocliente = new Servicios();
            return Json(ocliente, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult listarDisponible(string FechaE)
        {
            var data = new Model.Neg.ProductoNeg().ReadDisponible(FechaE);
            var json = new { data };
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult listardetalle (int id)
        {
            var data = new Model.Neg.ProductoNeg().ReadDetalle(id);
            var json = new { data };
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult listarFactura()
        {
            var data = new Model.Neg.ProductoNeg().ReadVistaF();
            var json = new { data };
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult listarDeuda()
        {
            var data = new Model.Neg.ProductoNeg().ReadVistaD();
            var json = new { data };
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult listarRecibo(int ID)
        {
            var data = new Model.Neg.ProductoNeg().ReadVistaRecibo(ID);
            var json = new { data };
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult listar()
        {
            var data = new Model.Neg.ProductoNeg().ReadVista();
            var json = new { data };
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult listarT()
        {
            var data = new Model.Neg.ProductoNeg().ReadVistaT();
            var json = new { data };
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GuardarP(float Impuesto, float Subtotal, float Total, List<DetalleFactura> ListadoDetalle)
        {
            int ID_Proforma = 0;
            string Fecha = DateTime.Now.ToString("yyyy-MM-dd hh:mm:ss");

            if (Total == 0)
            {

            }
            else
            {
                if (ID_Proforma != 0)
                {

                }
                else
                {

                    //REGISTRO DE PROFORMA
                    Proforma objFactura = new Proforma(Fecha, Subtotal, Impuesto, Total);
                    ID_Proforma = objFacturaNeg.createP(objFactura);
                    
                    if (ID_Proforma == 0)
                    {

                    }
                    else
                    {
                        //Registro del Detalle
                        foreach (var data in ListadoDetalle)
                        {
                            int IdProducto = Convert.ToInt32(data.ID_Servicio.ToString());
                            int cantidad = Convert.ToInt32(data.Cantidad.ToString());
                            double subtotal = Convert.ToDouble(data.SubTotal.ToString());
                            DetalleFactura objDetalleVenta =
                            new DetalleFactura(ID_Proforma, 1,IdProducto, cantidad, subtotal);
                            objDetalleFacturaNeg.createP(objDetalleVenta);
                        }
                    }
                }
            }
            return Json(ID_Proforma);
        }

    }
}

CapaPresentacion/Views/Venta/Historial.cshtml
@section scripts{
    <script>
        var TablaAlmacen;
        var Tabla_S;
        var Metodo = "Efectivo";
        var Codigo;
        var Debido;
        var Contador = 0;
        $(document).ready(function () {
            TablaAlmacen = $('#tbalmacen').DataTable({
                "ajax": {
                    "url": "@Url.Action("listarDeuda", "Servicio")",
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [
                    { "data": "ID_Servicio" },
                    { "data": "Descripcion" },
                    { "data": "Cantidad" },
                    { "data": "Estado" },
                    { "data": "Precio" },
                    { "data": "Categoria" }
                ],
                "language": {
                    url: "https://cdn.datatables.net/plug-ins/1.12.1/i18n/es-ES.json"
                },

                dom: 'Bfrtip',
                buttons: [
                    'excel',
                    'print'
                ]
            });

            $('#tbalmacen tbody').on('dblclick', 'tr', function () {
                Codigo = $(this).children().eq('0').text();
                Debido = $(this).children().eq('3').text();
                Recibo();

            });

        });

       
        function AbrirModal()
        {
            $('#TI').val(Debido);
            $('#ID_Evento').val(Codigo);
            $('#Monto').val("");
            $('#Modal').modal('hide');
            $('#ModalRecibo').modal('show');
            $('#Smetodo').change(function () {
                if ($(this).val() === "Cheque") {
                    Metodo = "Cheque";
                    var x = document.getElementById("Cheque");
                    x.style.display = "block";
                    var x = document.getElementById("Metodos");
                    x.style.display = "none";
                    $('#Efectivo').val(0.00);
                    $('#PCheque').val(0.00);
                } else if ($(this).val() === "EC") {
                    Metodo = "T/C";
                    var x = document.getElementById("Cheque");
                    x.style.display = "block";
                    var x = document.getElementById("Metodos");
                    x.style.display = "block";
                } else if ($(this).val() === "Efectivo"){
                    Metodo = "Efectivo";
                    $('#Efectivo').val(0.00);
                    $('#PCheque').val(0.00);
                    var x = document.getElementById("Cheque");
                    x.style.display = "none";
                    var x = document.getElementById("Metodos");
                    x.style.display = "none";
                }
            });

        }

        function Recibo()
        {
            if (Contador == 0)
            {
                Contador = 1;
                Tabla_S = $('#tbr').DataTable({
                    "ajax": {
                        "url": "@Url.Action("listarRecibo", "Servicio")" + "?ID=" + Codigo,
                        "type": "GET",
                        "datatype": "json"
                    },
                    "columns": [
                        { "data": "ID_Recibo" },
                        { "data": "Fecha" },
                        { "data": "Nombre" },
                        { "data": "Forma" },
                        { "data": "Monto" }
                    ],
                    dom: 'Bfrtip',
                    buttons: [
                        {
                            text: 'Agregar Nuevo',
                            attr: { class: 'btn btn-success btn-sm' },
                            action: function (e, dt, node, config) {
                                AbrirModal()
                            }
                        }
                    ],
                });

                $('#tbr tbody').on('dblclick', 'tr', function () {

                    var CodigoR = $(this).children().eq('0').text();
                    var caracteristicas = "height=600,width=800,scrollTo,resizable=1,scrollbars=1,location=0";
                    nueva = window.open("/Servicio/Recibo?ID=" + parseInt(CodigoR), 'popup', caracteristicas);

                });
            }
            else
            {
                Tabla_S.ajax.reload();
            }
            $('#Modal').modal('show');
        }

        function Guardar()
        {
            if (parseFloat($("#Monto").val()) > (parseFloat($("#TI").val())) ) {
                swal("Mensaje", "El monto no debe ser mayor al saldo", "error");
                return;
            }

            if (Metodo == "Efectivo y Cheque" && parseFloat($("#Monto").val()) != (parseFloat($('#PCheque').val()) + parseFloat($('#PEfec').val()))) {
                swal("Mensaje", "El Monto debe sumar lo mismo que el adelanto", "error");
                return;
            }

            Monto = $('#Monto').val();
            if (Metodo == "Efectivo") {
                Efectivo = $('#Monto').val();
                Cheque = 0;
            } else if (Metodo == "Cheque") {
                Cheque = $('#Monto').val();
                Efectivo = 0;
            }
            else if (Metodo == "T/C"){
                Efectivo = $('#PEfec').val();
                Cheque = $('#PCheque').val();
            }
            var f = new Date();
            var Fecha = (f.getFullYear() + "/" + (f.getMonth() + 1) + "/" + f.getDate());

            var $data = {

                ORecibo: {
                    ID_Evento: parseInt(Codigo),
                    Monto: $("#Monto").val(),
                    Forma: Metodo,
                    Fecha: Fecha,
                    Banco: $("#Banco").val(),
                    Cheque: Cheque,
                    Efectivo: Efectivo,
                    Concepto: $("#Concepto").val()
                }
            }

            jQuery.ajax({
                url: "@Url.Action("GuardarRecibo", "Servicio")",
                type: "POST",
                data: JSON.stringify($data),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    TablaAlmacen.ajax.reload();
                    $('#ModalRecibo').modal('hide');
                    var caracteristicas = "height=600,width=800,scrollTo,resizable=1,scrollbars=1,location=0";
                    nueva = window.open("/Servicio/Recibo?ID=" + data, '_blank');

                },
                error: function (error) {
                    console.log(error)
                },
                beforeSend: function () {
                }
            });
        }
    </script>        
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Almacen</title>
</head>
<body>

    <div class="row m-4">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    REGISTRO DEUDAS
                </div>
                <div class="card-body">
                    <table class="hover" id="tbalmacen" style="width:100%">
                        <thead>
                            <tr>
                                <th><font color="blue">ID Evento</font></th>
                                <th><font color="blue">Nombre</font></th>
                                <th><font color="blue">Pagado</font></th>
                                <th><font color="blue">Debido</font></th>
                                <th><font color="blue">Total</font></th>
                                <th><font color="blue">Estado</font></th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="ModalRecibo" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" style="max-width: 700px!important;" role="document">
            <div class="modal-content">
                <div class="modal-header">
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <input type="hidden" id="ID_Evento">
                                <label for="Nombre">Debido:</label>
                                <input type="text" class="form-control" id="TI">
                                <label for="Nombre">Monto:</label>
                                <input type="text" class="form-control" id="Monto">
                            </div>
                            <div class="form-group">
                                <label for="Concepto">Metodo de Pago:</label>
                                <select class="form-control" id="Smetodo">
                                    <option value="Efectivo">En Efectivo</option>
                                    <option value="Cheque">Cheque</option>
                                    <option value="EC">Efectivo y Cheque</option>
                                </select>
                            </div>
                            <div class="form-group" id="Cheque" style="display: none">
                                <label for="Banco">Banco:</label>
                                <input type="text" class="form-control" id="Banco" value="">
                            </div>

                            <div class="form-group" id="Metodos" style="display: none">
                                <label for="Efectivo">Pago en efectivo:</label>
                                <input type="text" class="form-control" id="PEfec" value="0">
                                <label for="PCheque">Pago con cheque:</label>
                                <input type="text" class="form-control" id="PCheque" value="0">
                            </div>

                            <div class="form-group">
                                <label for="Concepto">En concepto de:</label>
                                <input type="text" class="form-control" id="Concepto">

                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">

                    <button type="button" class="btn btn-lg" data-bs-dismiss="modal">Cerrar</button>
                    <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="Modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" style="max-width: 1350px!important;" role="document">
            <div class="modal-content">

                <div class="modal-body">

                    <div class="row m-4">
                        <div class="col-sm-12">
                            <div class="card">
                              
                                <div class="card-body">
                                    <table class="hover" id="tbr" style="width:100%">
                                        <thead>
                                            <tr>
                                                <th><font color="blue">ID Recibo</font></th>
                                                <th><font color="blue">Fecha</font></th>
                                                <th><font color="blue">Nombre</font></th>
                                                <th><font color="blue">Forma de Pago</font></th>
                                                <th><font color="blue">Monto</font></th>
                                            </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>


</body>
</html>

CapaPresentacion/Views/Venta/Pagar.cshtml
@section scripts{
    <script>
        var TablaAlmacen;
        $(document).ready(function () {
            TablaAlmacen = $('#tbalmacen').DataTable({
                "ajax": {
                    "url": "@Url.Action("listarFactura", "Servicio")",
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [
                    { "data": "ID_Servicio" },
                    { "data": "Descripcion" },
                    { "data": "Precio" },
                    { "data": "Categoria" }
                ],
                dom: 'Bfrtip',
            });

            $('#tbalmacen tbody').on('dblclick', 'tr', function () {
                var ID;
                ID = $(this).children().eq('0').text();
                var caracteristicas = "height=800,width=1000,scrollTo,resizable=1,scrollbars=1,location=0";
                nueva = window.open("/Venta/Factura?ID=" + parseInt(ID), 'popup', caracteristicas);
            });

        });

        function ListarServicio(ID)
        {
              TablaAlmacen = $('#tba').DataTable({
                "ajax": {
                      "url": "@Url.Action("listardetalle", "Servicio")" + "?id=" + ID,
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [                   
                    { "data": "Descripcion" },
                    { "data": "Precio" },
                    { "data": "Cantidad" },
                     { "data": "ID_Servicio" }
                ],
                dom: 'Bfrtip',         

            });
            $('#formModal').modal('show');

        }

        function AbrirModal($idAlmacen)
        {
          $("#txtIdProducto").val($idAlmacen);
             // var $ID_Categoria = document.getElementById("Categoria").value;

            if ($idAlmacen != 0) {

                jQuery.ajax({
                    url: "@Url.Action("Obtener","Servicio")" + "?idAlmacen=" + $idAlmacen,
                    type: "GET",
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {

                        if (data != null) {

                            $("#txtDescripcion").val(data.Descripcion);
                            $("#txtPrecio").val(data.Precio);
                            $ID_Categoria.val(data.ID_Categoria);
                            $("#txtCantidad").val(data.Cantidad);
                        }

                    }
                });
              }
              else {
                $("#txtDescripcion").val("");
                $("#txtPrecio").val("");
                  $("#txtCantidad").val("");
            }

              $('#formModal').modal('show');

        }

         function Eliminar($idAlmacen) {
                console.log = $idAlmacen
                if (confirm("¿Realmente desea eliminar?")) {

                    jQuery.ajax({
                        url: "@Url.Action("Eliminar", "Servicio")" + "?idAlmacen=" + $idAlmacen,
                        type: "POST",
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {
                            TablaAlmacen.ajax.reload();
                        }
                    });
                }
            }

        function Guardar() {
            var ID_Categoria = document.getElementById("Categoria").value;
            var $data = {
                OAlmacen: {
                    ID_Servicio: parseInt($("#txtIdProducto").val()),
                    Descripcion: $("#txtDescripcion").val(),
                    Precio: $("#txtPrecio").val(),
                    ID_Categoria: ID_Categoria.val(),
                    Cantidad: $("#txtCantidad").val()
                }

            }

            jQuery.ajax({
                url: "@Url.Action("Guardar", "Cliente")",
                type: "POST",
                data: JSON.stringify($data),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    TablaAlmacen.ajax.reload();
                    $('#formModal').modal('hide');

                },
                error: function (error) {
                    console.log(error)
                },
                beforeSend: function () {
                }
            });
        }
    </script>        
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Almacen</title>
</head>
<body>

    <div class="row m-4">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    REGISTRO EVENTOS
                </div>
                <div class="card-body">
                    <table class="hover" id="tbalmacen" style="width:100%">
                        <thead>
                            <tr>
                                <th><font color="blue">ID Factura</font></th>
                                <th><font color="blue">Nombre</font></th>
                                <th><font color="blue">Total</font></th>
                                <th><font color="blue">Fecha</font></th>
                                
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="formModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" style="max-width: 1300px!important;" role="document">
            <div class="modal-content">
                <div class="modal-header">                
                </div>
                <div class="modal-body">

                    <div class="row m-4">
                        <div class="col-sm-12">
                            <div class="card">
                                <div class="card-header">
                                </div>
                                <div class="card-body">
                                    <table class="display responsive nowrap" id="tba" style="width:100%">
                                        <thead>
                                            <tr>                                            
                                                <th>Descripcion</th>
                                                <th>Precio</th>
                                                <th>Cantidad</th>
                                                <th>Subtotal</th>
                                            </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cerrar</button>
                    <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
                </div>
            </div>
        </div>
    </div>

</body>
</html>