CapaPresentacion/Controllers/AccesoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

using CapaPresentacion.Models;
using Model.Neg;

namespace CapaPresentacion.Controllers
{
    public class AccesoController : Controller
    {
        private UsuarioNeg ObjUsuarioNeg;
        // GET: Acceso
        public AccesoController()
        {
            ObjUsuarioNeg = new UsuarioNeg();         
        }

        public ActionResult Inicio()
        {
            ViewData["Cliente"] = ObjUsuarioNeg.ReadC();
            ViewData["Evento"] = ObjUsuarioNeg.ReadE();
            ViewData["Almacen"] = ObjUsuarioNeg.ReadA();
            ViewData["Transporte"] = ObjUsuarioNeg.ReadT();
            return View();
        }

        public ActionResult Login()
        {            
            return View();
        }
     
        [HttpPost]
        public ActionResult InicioS(Model.Entity.Usuario oUsuario)
        {           
            int ID = ObjUsuarioNeg.Read(oUsuario);

            if (ID != 0)
            {               
                Session["User"] = oUsuario;
                //SqlConnection con = new SqlConnection(Cadena);
                //con.Open();
                //SqlCommand cm = new SqlCommand("select concat(Nombre_E, Apellido_E) from Empleado where ID_Empleado = " + oUsuario.ID_Empleado, con);
                //SqlDataReader dr = cm.ExecuteReader();
                //while (dr.Read())
                //{
                //    string NombreUsuario = dr.GetString(0);
                //}
                return Json(ID);
            }
            else
            {
                return Json(ID);
            }
        }
    }
}

CapaPresentacion/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.Entity;
using Model.Neg;

namespace CapaPresentacion.Controllers
{
    public class AdminController : Controller
    {
        private UsuarioNeg ObjUsuarioNeg;
        // GET: Acceso
        public AdminController()
        {
            ObjUsuarioNeg = new UsuarioNeg();
        }

        public ActionResult Inicio()
        {
            ViewData["Cliente"] = ObjUsuarioNeg.ReadC();
            ViewData["Evento"] = ObjUsuarioNeg.ReadE();
            ViewData["Almacen"] = ObjUsuarioNeg.ReadA();
            ViewData["Transporte"] = ObjUsuarioNeg.ReadT();
            return View();
        }

        public ActionResult Empleado()
        {
            return View();
        }

        public ActionResult Almacen()
        {
            return View();
        }

        public ActionResult Proforma()
        {
            return View();
        }

        public ActionResult Transporte()
        {
            return View();
        }
        public ActionResult Historial()
        {
            return View();
        }

        public ActionResult Cliente()
        {
            return View();
        }

        // GET: Admin
        public ActionResult Usuario()
        {
            return View();
        }

        [HttpGet]
        public JsonResult listarE()
        {
            var data = new Model.Neg.UsuarioNeg().listarE();
            var json = new { data };
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult listarER()
        {
            var data = new Model.Neg.UsuarioNeg().listarER();
            var json = new { data };
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult listar()
        {
            var data = new Model.Neg.UsuarioNeg().listar();
            var json = new { data };
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Guardar(Usuario OUsuario)
        {
            OUsuario.Pass = "123456789";
            bool respuesta = true;
            try
            {
                if (OUsuario.ID_Empleado != 0)
                {                 
                    Model.Neg.UsuarioNeg.Agregar(OUsuario);
                }
                else
                {
                   
                }
            }
            catch
            {
                respuesta = false;
            }

            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarE(Empleado OCliente)
        {
            bool respuesta = true;
            try
            {
                if (OCliente.ID_Empleado == 0)
                {
                    Model.Neg.UsuarioNeg.AgregarE(OCliente);
                }
                else
                {
                    Model.Neg.UsuarioNeg.ActualizarE(OCliente);
                }
            }
            catch
            {
                respuesta = false;
            }

            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult EliminarU(int IdCliente)
        {
            bool respuesta = true;
            try
            {
                UsuarioNeg.EliminarU(IdCliente);
            }
            catch
            {
                respuesta = false;
            }
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }

    }
}

CapaPresentacion/Controllers/VentaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaPresentacion.Models;
using Model.Entity;
using Model.Neg;

namespace CapaPresentacion.Controllers
{
    public class VentaController : Controller
    {
        // GET: Venta

        private EventoNeg objEventoNeg;
        
        private ClienteNeg objClienteNeg;
        private ProductoNeg objProductoNeg;
        private FacturaNeg objFacturaNeg;
        private DetalleFacturaNeg objDetalleFacturaNeg;
        List<Servicios> Lista;

        public VentaController()
        {
            objEventoNeg = new EventoNeg();
            objClienteNeg = new ClienteNeg();
            objProductoNeg = new ProductoNeg();
            objFacturaNeg = new FacturaNeg();
            objDetalleFacturaNeg = new DetalleFacturaNeg();
        }

        public ActionResult Historial()
        {
            return View();
        }


        public ActionResult Registro()
        {
            Lista = objProductoNeg.ReadVista();
            return View(Lista);
        }

        public ActionResult Contrato(int ID)
        {
            Evento Cabeza= new EventoNeg().VistaC(ID);
            ViewData["Fecha"] = Cabeza.Fecha;
            ViewData["FechaC"] = Cabeza.FechaF;
            ViewData["Observacion"] = Cabeza.Observaciones;
            ViewData["Direccion"] = Cabeza.Direccion;
            ViewData["Adelanto"] = Cabeza.Adelanto;
            ViewData["Nombre"] = Cabeza.Nombre;
            ViewData["Total"] = Cabeza.ID_Cliente;
            ViewData["Horai"] = Cabeza.HoraI;
            ViewData["Horaf"] = Cabeza.HoraF;

            return View();
        }

        public ActionResult Recibo(int ID)
        {
            Recibo Cabeza = new FacturaNeg().VistaR(ID);
            ViewData["Fecha"] = Cabeza.Fecha;
            ViewData["Nombre"] = Cabeza.Nombre;
            ViewData["Metodo"] = Cabeza.Forma;
            ViewData["Monto"] = Cabeza.Monto;
            return View();
        }

        public ActionResult Factura(int ID)
        {
            Factura Cabeza = new FacturaNeg().VistaF(ID);
            List<Servicios> ListadoDetalle = new FacturaNeg().VistaDF(ID);
            ViewData["Fecha"] = Cabeza.Fecha;
            ViewData["Nombre"] = Cabeza.Nombre;
            ViewData["Cel"] = Cabeza.Telefono;
            ViewData["ID"] = Cabeza.ID_Factura;
            ViewData["Suma"] = Cabeza.Subtotal;
            ViewData["Descuento"] = Cabeza.Descuento;
            ViewData["Subtotal"] = Cabeza.Total - Cabeza.Impuesto;
            ViewData["Iva"] = Cabeza.Impuesto;
            ViewData["Total"] = Cabeza.Total;
            ViewData["Direccion"] = Cabeza.Direccion;
            return View(ListadoDetalle);
        }

        public ActionResult Proforma(int ID)
        {
            Proforma Cabeza = new FacturaNeg().VistaP(ID);
            List<Servicios> ListadoDetalle = new FacturaNeg().VistaD(ID);
            ViewData["Fecha"] = Cabeza.Fecha;
            ViewData["Subtotal"] = Cabeza.Total - Cabeza.Impuesto;
            ViewData["Iva"] = Cabeza.Impuesto;
            ViewData["Total"] = Cabeza.Total;
            return View(ListadoDetalle);
        }

        public ActionResult Servicio()
        {
            var data = new Model.Neg.ProductoNeg().ReadVista();
            var json = new { data };
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        public ActionResult MostrarClientes()
        {
            List<Cliente_Venta> lista = objClienteNeg.findAll();
            return View(lista);
        }

        [HttpPost]//para buscar clientes
        public ActionResult MostrarClientes(string txtnombre, string txtappaterno, string txtdni, long txtcliente = -1)
        {
            if (txtnombre == "")
            {
                txtnombre = "-1";
            }
            if (txtappaterno == "")
            {
                txtappaterno = "-1";
            }
            if (txtdni == "")
            {
                txtdni = "-1";
            }
            Cliente_Venta objCliente = new Cliente_Venta();
            objCliente.Nombre = txtnombre;
            objCliente.ID_Cliente = (int)txtcliente;
            objCliente.Apellido = txtappaterno;
            objCliente.Cedula = txtdni;

            List<Cliente_Venta> cliente = objClienteNeg.findAllClientes(objCliente);
            return View(cliente);
        }

        [HttpPost]
        public ActionResult Seleccionar(int ID_Servicio)
        {
            Servicios objProducto = new Servicios(ID_Servicio);
            objProductoNeg.find(objProducto);
            return Json(objProducto, JsonRequestBehavior.AllowGet);
        }

        public ActionResult PruebaJson()
        {  // escribir la url directa  para ver el formato      
            List<Producto> lista = objProductoNeg.findAll();
            return Json(lista, JsonRequestBehavior.AllowGet);

        }

        [HttpGet]
        public JsonResult Read()
        {
            var data = new Model.Neg.ProductoNeg().Read();
            var json = new { data };
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GuardarVenta(string Fecha, int Descuento, string FechaF, 
            int Adelanto, string Hora_I, string Hora_F , string Observacion, 
            string Direccion, int ID_Empleado, int Id_Cliente, string Metodo, 
            float Efectivo, float Cheque, string Banco, string Concepto,
            string Total, List<DetalleFactura> ListadoDetalle)
        {
            
            //Evento(ID_Evento, ID_Cliente, ID_Empleado, Fecha_Evento) , List<DetalleVenta> ListadoDetalle
            //Factura(ID_Factura,Impuesto,Total)
            //Detalle_Factura(ID_Detalle,ID_Factura,ID_Evento,ID_Servicio,Cantidad,subtotal)                    
            int ID_Factura = 0;
            int ID_Evento = 0;
            int ID_Recibo = 0;
            int Subtotal = (int)float.Parse(Total);
            int Impuesto = ((int.Parse(Total) - Descuento) * 15) / 100;
            float total = (int.Parse(Total) - Descuento) + Impuesto;

            if (Fecha == "" || Id_Cliente == 0 || Total == "")
            {

            }
            else
            {
                //   total = Convert.ToDouble(Total);

                //REGISTRO DE VENTA
                Evento objEvento = new Evento(Id_Cliente, ID_Empleado, Fecha, Direccion, Observacion, Adelanto, Hora_I, Hora_F);
                ID_Evento = objEventoNeg.create(objEvento);
                if (ID_Evento == 0)
                {

                }
                else
                {
                    Session["id_Evento"] = ID_Evento;

                    Recibo objRecibo = new Recibo(FechaF, ID_Evento, Adelanto, Metodo, Efectivo, Cheque, Banco, Concepto);
                    ID_Recibo = objFacturaNeg.createR(objRecibo);
                   

                    //REGISTRO DE FACTURA
                    Factura objFactura = new Factura(FechaF, Subtotal, Impuesto, total, Descuento);
                    ID_Factura = objFacturaNeg.create(objFactura);

                    if (ID_Factura == 0)
                    {

                    }
                    else
                    {
                        //Registro del Detalle
                        foreach (var data in ListadoDetalle)
                        {
                            int IdProducto = Convert.ToInt32(data.ID_Servicio.ToString());
                            int cantidad = Convert.ToInt32(data.Cantidad.ToString());
                            double subtotal = Convert.ToDouble(data.SubTotal.ToString());
                            DetalleFactura objDetalleVenta =
                            new DetalleFactura(ID_Factura, ID_Evento, IdProducto, cantidad, subtotal);
                            objDetalleFacturaNeg.create(objDetalleVenta);
                        }
                    }
                }
            }
            Factura objFin = new Factura("h", 100,ID_Evento, ID_Factura, ID_Recibo);

            return Json(objFin);
        }      
    }
}

CapaPresentacion/Views/Shared/_Layout_Admin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Admin</title>
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/Content/adminlte/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Content/adminlte/dist/css/adminlte.min.css">
    
    @RenderSection("Styles", required: false)

    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/Data/css")
</head>
<body>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" rel="stylesheet" />


    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a href="@Url.Action("Inicio","Admin")" class="nav-link">Inicio</a>
            </li>
        </ul>

        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">

            <!-- Notifications Dropdown Menu -->

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="@Url.Action("InicioRegistro","Home")">Usuario</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="@Url.Action("Login","Acceso")" onclick="Function()">Cerrar Sesion</a></li>
                </ul>
            </li>


            <!-- Boton para pantalla completa -->
            <li class="nav-item">
                <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                    <i class="fas fa-expand-arrows-alt"></i>
                </a>
            </li>
        </ul>
    </nav>

    @*
        Slidebar
    *@

    <aside class="main-sidebar sidebar-light-primary elevation-4">
        <!-- Brand Logo -->
        <a href="index3.html" class="brand-link">
            <img src="~/Content/Img/ML.png" alt="IMG" class="brand-image img-circle elevation-3" style="opacity: .8">
            <div class="navbar-brand ps-2"><font color="blue">SAFE</font></div>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

                    <li class="nav-item">
                        <div class="navbar-brand ps-2" border="1"><font color="blue">Evento</font></div>
                        <a href="@Url.Action("Registro","Venta")" class="nav-link">

                            <i class="nav-icon fas fa-clipboard"></i>
                            <p>
                                Registro Venta
                            </p>
                        </a>
                    </li>

                    <li class="nav-item">
                        <div class="navbar-brand ps-2"><font color="blue">Control</font></div>

                        <a href="@Url.Action("Cliente","Admin")" class="nav-link">
                            <i class="nav-icon fas fa-book-open"></i>
                            <p>
                                Clientes
                            </p>
                        </a>


                    <li class="nav-item menu-open">

                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-boxes"></i>
                            <p>
                                Servicios
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="@Url.Action("Almacen","Admin")" class="nav-link active">
                                    <i class="fas fa-warehouse nav-icon"></i>
                                    <p>Almacen</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("Transporte","Admin")" class="nav-link">
                                    <i class="fas fa-truck-moving nav-icon"></i>
                                    <p>Transporte</p>
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class="nav-item">

                        <div class="navbar-brand ps-2"><font color="blue">Facturacion</font></div>

                        <a href="@Url.Action("Historial","Admin")" class="nav-link">
                            <i class="nav-icon fas fa-book-open"></i>
                            <p>
                                Historial
                            </p>
                        </a>

                        <a href="@Url.Action("Proforma","Admin")" class="nav-link">
                            <i class="nav-icon fas fa-book-open"></i>
                            <p>
                                Cotizar
                            </p>
                        </a>
                    </li>

                    <li class="nav-item">
                        <div class="navbar-brand ps-2" border="1"><font color="blue">Empleados</font></div>
                        <a href="@Url.Action("Empleado","Admin")" class="nav-link">
                            <i class="nav-icon fas fa-book-open"></i>
                            <p>
                                Empleados
                            </p>
                        </a>

                        <a href="@Url.Action("Usuario","Admin")" class="nav-link">
                            <i class="nav-icon fas fa-book-open"></i>
                            <p>
                                Usuarios
                            </p>
                        </a>

                    </li>

                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>

    @RenderBody()

    @*
        Footer
    *@

    <footer class="main-footer">
        <!-- To the right -->
        <div class="float-right d-none d-sm-inline">
            Anything you want
        </div>
        <!-- Default to the left -->
        <strong>Copyright &copy; 2022 <a href="#">ML</a></strong>
    </footer>

    <script>
        function Modal() {
            $('#Modal').modal('show');
        }

        function enter1() {
            var x = document.getElementById("a");
            x.style.display = "none";
            var x = document.getElementById("b");
            x.style.display = "block";
        }

        function enter() {
            var x = document.getElementById("boton");
            x.style.display = "none";
            var x = document.getElementById("a");
            x.style.display = "block";
        }

    </script>



    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>

    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.3/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.html5.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.print.min.js"></script>



    <!-- jQuery -->
    <script src="~/Content/adminlte/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/Content/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Content/adminlte/dist/js/adminlte.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>


    <div class="modal fade" id="Modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <center>
                        <h5 class="modal-title" id="exampleModalLabel">Cambiar Contraseña</h5>
                    </center>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <input type="hidden" id="txtIdCliente" />
                            <div id="boton" class="form-group">
                                <center><label for="txtNombre">Ingrese contraseña actual:</label></center>
                                <input type="text" class="form-control" id="txtNombre">
                                <button class="form-control" onclick="enter()">Siguiente</button>
                            </div>
                            <div id="a" style="display:none" class="form-group">
                                <center><label for="txtNombre">Ingrese nueva contraseña:</label></center>
                                <input type="text" class="form-control" id="txt">
                                <button class="form-control" onclick="enter1()">Siguiente</button>
                            </div>
                            <div id="b" style="display:none" class="form-group">
                                <center> <label for="txtNombre">Ingrese nuevamente la contraseña:</label></center>
                                <input type="text" class="form-control" id="txtNombre">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-lg" data-bs-dismiss="modal">Cerrar</button>
                    <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
                </div>
            </div>
        </div>
    </div>



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstra")
    @Scripts.Render("~/Content/Data/js")
    @Scripts.Render("~/bundles/complementos")

    @RenderSection("Scripts", required: false)

</body>
</html>

CapaPresentacion/Views/Shared/_Layout_Inicio.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Admin</title>
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/Content/adminlte/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Content/adminlte/dist/css/adminlte.min.css">
    
    @RenderSection("Styles", required: false)

    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/Data/css")
</head>
<body>


   

    @RenderBody()

    @*
        Footer
    *@

    <footer class="main-footer">
        <!-- To the right -->
        <div class="float-right d-none d-sm-inline">
            Anything you want
        </div>
        <!-- Default to the left -->
        <strong>Copyright &copy; 2022 <a href="#">ML & Compañia Limitada</a>.</strong> .
    </footer>

    <!-- jQuery -->
    <script src="~/Content/adminlte/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/Content/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Content/adminlte/dist/js/adminlte.min.js"></script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstra")
    @Scripts.Render("~/Content/Data/js")
    @Scripts.Render("~/bundles/complementos")

    @RenderSection("Scripts", required: false)

</body>
</html>